language: go

script:
  - go test -covermode count -coverprofile coverage.txt -args -alhoc
after_success:
  # See https://github.com/codecov/example-go
  - bash <(curl -s https://codecov.io/bash)

go:
  - 1.6
  - 1.7
  - tip
